#ifndef COL_H
#define COL_H
const char *glade_str_col[] = {
	"<?xml version=\"1.0\"?>\n", 
	"<interface>\n", 
	"  <requires lib=\"gtk+\" version=\"2.16\"/>\n", 
	"  <!-- interface-naming-policy project-wide -->\n", 
	"  <object class=\"GtkColorSelectionDialog\" id=\"colorseldiag\">\n", 
	"    <property name=\"border_width\">5</property>\n", 
	"    <property name=\"type_hint\">normal</property>\n", 
	"    <child internal-child=\"color_selection\">\n", 
	"      <object class=\"GtkColorSelection\" id=\"colorsel\">\n", 
	"        <property name=\"visible\">True</property>\n", 
	"        <property name=\"border_width\">5</property>\n", 
	"        <property name=\"orientation\">vertical</property>\n", 
	"        <property name=\"has_palette\">True</property>\n", 
	"        <property name=\"current_color\">#ffffffffffff</property>\n", 
	"        <child>\n", 
	"          <placeholder/>\n", 
	"        </child>\n", 
	"        <child>\n", 
	"          <placeholder/>\n", 
	"        </child>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"    <action-widgets>\n", 
	"      <action-widget response=\"0\">colorsel_help</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_ok</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_cancel</action-widget>\n", 
	"    </action-widgets>\n", 
	"    <child internal-child=\"help_button\">\n", 
	"      <object class=\"GtkButton\" id=\"colorsel_help\">\n", 
	"        <property name=\"label\">gtk-help</property>\n", 
	"        <property name=\"can_focus\">True</property>\n", 
	"        <property name=\"can_default\">True</property>\n", 
	"        <property name=\"receives_default\">True</property>\n", 
	"        <property name=\"use_underline\">True</property>\n", 
	"        <property name=\"use_stock\">True</property>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"    <action-widgets>\n", 
	"      <action-widget response=\"0\">colorsel_help</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_ok</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_cancel</action-widget>\n", 
	"    </action-widgets>\n", 
	"    <child internal-child=\"cancel_button\">\n", 
	"      <object class=\"GtkButton\" id=\"colorsel_cancel\">\n", 
	"        <property name=\"label\">gtk-cancel</property>\n", 
	"        <property name=\"visible\">True</property>\n", 
	"        <property name=\"can_focus\">True</property>\n", 
	"        <property name=\"can_default\">True</property>\n", 
	"        <property name=\"receives_default\">True</property>\n", 
	"        <property name=\"use_underline\">True</property>\n", 
	"        <property name=\"use_stock\">True</property>\n", 
	"        <signal name=\"clicked\" handler=\"on_colorsel_cancel_clicked\"/>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"    <action-widgets>\n", 
	"      <action-widget response=\"0\">colorsel_help</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_ok</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_cancel</action-widget>\n", 
	"    </action-widgets>\n", 
	"    <child internal-child=\"ok_button\">\n", 
	"      <object class=\"GtkButton\" id=\"colorsel_ok\">\n", 
	"        <property name=\"label\">gtk-ok</property>\n", 
	"        <property name=\"visible\">True</property>\n", 
	"        <property name=\"can_focus\">True</property>\n", 
	"        <property name=\"can_default\">True</property>\n", 
	"        <property name=\"receives_default\">True</property>\n", 
	"        <property name=\"use_underline\">True</property>\n", 
	"        <property name=\"use_stock\">True</property>\n", 
	"        <signal name=\"clicked\" handler=\"on_colorsel_ok_clicked\"/>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"    <action-widgets>\n", 
	"      <action-widget response=\"0\">colorsel_help</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_ok</action-widget>\n", 
	"      <action-widget response=\"0\">colorsel_cancel</action-widget>\n", 
	"    </action-widgets>\n", 
	"  </object>\n", 
	"</interface>\n", 
	"<?xml version=\"1.0\"?>\n", 
	"<interface>\n", 
	"  <requires lib=\"gtk+\" version=\"2.16\"/>\n", 
	"  <!-- interface-naming-policy project-wide -->\n", 
	"  <object class=\"GtkWindow\" id=\"winMain\">\n", 
	"    <property name=\"title\" translatable=\"yes\">Comm v2.0</property>\n", 
	"    <property name=\"default_width\">600</property>\n", 
	"    <property name=\"default_height\">300</property>\n", 
	"    <signal name=\"focus_in_event\" handler=\"on_winMain_focus_in_event\"/>\n", 
	"    <child>\n", 
	"      <object class=\"GtkHBox\" id=\"hboxMain\">\n", 
	"        <property name=\"visible\">True</property>\n", 
	"        <child>\n", 
	"          <object class=\"GtkVBox\" id=\"vboxLeft\">\n", 
	"            <property name=\"width_request\">160</property>\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <property name=\"orientation\">vertical</property>\n", 
	"            <child>\n", 
	"              <object class=\"GtkVBox\" id=\"vboxControls\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"orientation\">vertical</property>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkHBox\" id=\"hboxCfg\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkVBox\" id=\"vboxCfgLabels\">\n", 
	"                        <property name=\"width_request\">106</property>\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"orientation\">vertical</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkLabel\" id=\"lblHost\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"label\" translatable=\"yes\">Host:</property>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"fill\">False</property>\n", 
	"                            <property name=\"position\">0</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkLabel\" id=\"lblName\">\n", 
	"                            <property name=\"width_request\">34</property>\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"label\" translatable=\"yes\">Name:</property>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"fill\">False</property>\n", 
	"                            <property name=\"position\">1</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">0</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkVBox\" id=\"vboxCfgText\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"orientation\">vertical</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkEntry\" id=\"entryHost\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"invisible_char\">&#x25CF;</property>\n", 
	"                            <signal name=\"activate\" handler=\"on_entryHost_activate\"/>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"position\">0</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkEntry\" id=\"entryName\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"invisible_char\">&#x25CF;</property>\n", 
	"                            <signal name=\"focus_out_event\" handler=\"on_entryName_focus_out_event\"/>\n", 
	"                            <signal name=\"activate\" handler=\"on_entryName_activate\"/>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"position\">1</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">1</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"expand\">False</property>\n", 
	"                    <property name=\"padding\">2</property>\n", 
	"                    <property name=\"position\">0</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkHBox\" id=\"hboxButtons\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkButton\" id=\"btnConnect\">\n", 
	"                        <property name=\"label\" translatable=\"yes\">Connect</property>\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"can_focus\">True</property>\n", 
	"                        <property name=\"receives_default\">True</property>\n", 
	"                        <signal name=\"clicked\" handler=\"on_btnConnect_clicked\"/>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">0</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkButton\" id=\"btnDisconnect\">\n", 
	"                        <property name=\"label\" translatable=\"yes\">Disconnect</property>\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"can_focus\">True</property>\n", 
	"                        <property name=\"receives_default\">True</property>\n", 
	"                        <signal name=\"clicked\" handler=\"on_btnDisconnect_clicked\"/>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">1</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"padding\">1</property>\n", 
	"                    <property name=\"position\">1</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"expand\">False</property>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">0</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"            <child>\n", 
	"              <object class=\"GtkHSeparator\" id=\"hseparatorLeft\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"expand\">False</property>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">1</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"            <child>\n", 
	"              <object class=\"GtkTreeView\" id=\"treeClients\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"can_focus\">True</property>\n", 
	"                <property name=\"reorderable\">True</property>\n", 
	"                <property name=\"fixed_height_mode\">True</property>\n", 
	"                <property name=\"rubber_banding\">True</property>\n", 
	"                <property name=\"enable_grid_lines\">horizontal</property>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">2</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"expand\">False</property>\n", 
	"            <property name=\"padding\">2</property>\n", 
	"            <property name=\"position\">0</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"        <child>\n", 
	"          <object class=\"GtkVSeparator\" id=\"vseparatorMain\">\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <property name=\"orientation\">vertical</property>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"expand\">False</property>\n", 
	"            <property name=\"padding\">2</property>\n", 
	"            <property name=\"position\">1</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"        <child>\n", 
	"          <object class=\"GtkVBox\" id=\"vboxRight\">\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <property name=\"orientation\">vertical</property>\n", 
	"            <child>\n", 
	"              <object class=\"GtkScrolledWindow\" id=\"scrolledwindowText\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"can_focus\">True</property>\n", 
	"                <property name=\"hscrollbar_policy\">automatic</property>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkTextView\" id=\"txtMain\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"can_focus\">True</property>\n", 
	"                    <property name=\"editable\">False</property>\n", 
	"                    <property name=\"wrap_mode\">word</property>\n", 
	"                    <signal name=\"button_press_event\" handler=\"on_txtMain_button_press_event\"/>\n", 
	"                    <signal name=\"key_press_event\" handler=\"on_txtMain_key_press_event\"/>\n", 
	"                  </object>\n", 
	"                </child>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">0</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"            <child>\n", 
	"              <object class=\"GtkHSeparator\" id=\"hseparatorText\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"expand\">False</property>\n", 
	"                <property name=\"position\">1</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"            <child>\n", 
	"              <object class=\"GtkHBox\" id=\"hboxIn\">\n", 
	"                <property name=\"height_request\">27</property>\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkEntry\" id=\"entryIn\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"can_focus\">True</property>\n", 
	"                    <property name=\"invisible_char\">&#x25CF;</property>\n", 
	"                    <property name=\"activates_default\">True</property>\n", 
	"                    <signal name=\"button_press_event\" handler=\"on_entryIn_button_press_event\"/>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"position\">0</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkButton\" id=\"btnSend\">\n", 
	"                    <property name=\"label\" translatable=\"yes\">Send</property>\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"can_focus\">True</property>\n", 
	"                    <property name=\"can_default\">True</property>\n", 
	"                    <property name=\"has_default\">True</property>\n", 
	"                    <property name=\"receives_default\">True</property>\n", 
	"                    <signal name=\"clicked\" handler=\"on_btnSend_clicked\"/>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"expand\">False</property>\n", 
	"                    <property name=\"fill\">False</property>\n", 
	"                    <property name=\"padding\">2</property>\n", 
	"                    <property name=\"position\">1</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"expand\">False</property>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">2</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"padding\">2</property>\n", 
	"            <property name=\"position\">2</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"  </object>\n", 
	"</interface>\n", 
	"<?xml version=\"1.0\"?>\n", 
	"<interface>\n", 
	"  <requires lib=\"gtk+\" version=\"2.16\"/>\n", 
	"  <!-- interface-naming-policy project-wide -->\n", 
	"  <object class=\"GtkWindow\" id=\"winPriv\">\n", 
	"    <child>\n", 
	"      <object class=\"GtkVBox\" id=\"vboxMain\">\n", 
	"        <property name=\"visible\">True</property>\n", 
	"        <property name=\"orientation\">vertical</property>\n", 
	"        <child>\n", 
	"          <object class=\"GtkTextView\" id=\"txtPriv\">\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <property name=\"can_focus\">True</property>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"position\">0</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"        <child>\n", 
	"          <object class=\"GtkHBox\" id=\"hboxSend\">\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <child>\n", 
	"              <object class=\"GtkEntry\" id=\"entryPriv\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"can_focus\">True</property>\n", 
	"                <property name=\"invisible_char\">&#x25CF;</property>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"position\">0</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"            <child>\n", 
	"              <object class=\"GtkButton\" id=\"btnPriv\">\n", 
	"                <property name=\"label\" translatable=\"yes\">Send</property>\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"can_focus\">True</property>\n", 
	"                <property name=\"receives_default\">True</property>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"expand\">False</property>\n", 
	"                <property name=\"fill\">False</property>\n", 
	"                <property name=\"position\">1</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"expand\">False</property>\n", 
	"            <property name=\"position\">1</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"  </object>\n", 
	"  <object class=\"GtkAction\" id=\"action1\"/>\n", 
	"</interface>\n", 
};
#endif
