#ifndef GFT_H
#define GFT_H
const char *glade_str_gft[] = {
	"<?xml version=\"1.0\"?>\n", 
	"<interface>\n", 
	"  <requires lib=\"gtk+\" version=\"2.16\"/>\n", 
	"  <!-- interface-naming-policy project-wide -->\n", 
	"  <object class=\"GtkWindow\" id=\"winMain\">\n", 
	"    <property name=\"title\" translatable=\"yes\">GFT v1.0</property>\n", 
	"    <signal name=\"focus_in_event\" handler=\"on_winMain_focus_in_event\"/>\n", 
	"    <child>\n", 
	"      <object class=\"GtkHBox\" id=\"hboxMain\">\n", 
	"        <property name=\"visible\">True</property>\n", 
	"        <property name=\"homogeneous\">True</property>\n", 
	"        <child>\n", 
	"          <object class=\"GtkFrame\" id=\"frmConnect\">\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <property name=\"label_xalign\">0</property>\n", 
	"            <property name=\"shadow_type\">out</property>\n", 
	"            <child>\n", 
	"              <object class=\"GtkVBox\" id=\"vboxConnect\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"orientation\">vertical</property>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkHBox\" id=\"hboxHost\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkLabel\" id=\"lblHost\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"label\" translatable=\"yes\">IP Address/Host:</property>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"expand\">False</property>\n", 
	"                        <property name=\"padding\">4</property>\n", 
	"                        <property name=\"position\">0</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <placeholder/>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"expand\">False</property>\n", 
	"                    <property name=\"position\">0</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkVBox\" id=\"vboxCmds\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"orientation\">vertical</property>\n", 
	"                    <property name=\"homogeneous\">True</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkHBox\" id=\"hboxButtansTop\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"homogeneous\">True</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkButton\" id=\"btnConnect\">\n", 
	"                            <property name=\"label\" translatable=\"yes\">Connect</property>\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"receives_default\">True</property>\n", 
	"                            <property name=\"border_width\">3</property>\n", 
	"                            <signal name=\"clicked\" handler=\"on_btnConnect_clicked\"/>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"position\">0</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkButton\" id=\"btnListen\">\n", 
	"                            <property name=\"label\" translatable=\"yes\">Listen</property>\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"receives_default\">True</property>\n", 
	"                            <property name=\"border_width\">3</property>\n", 
	"                            <signal name=\"clicked\" handler=\"on_btnListen_clicked\"/>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"position\">1</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">0</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkAlignment\" id=\"alignmentClose\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"left_padding\">60</property>\n", 
	"                        <property name=\"right_padding\">60</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkButton\" id=\"btnClose\">\n", 
	"                            <property name=\"label\" translatable=\"yes\">Close</property>\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"receives_default\">True</property>\n", 
	"                            <property name=\"border_width\">3</property>\n", 
	"                            <signal name=\"clicked\" handler=\"on_btnClose_clicked\"/>\n", 
	"                          </object>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">1</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"expand\">False</property>\n", 
	"                    <property name=\"position\">1</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkLabel\" id=\"lblTransfers\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"label\" translatable=\"yes\">Transfers</property>\n", 
	"                    <attributes>\n", 
	"                      <attribute name=\"underline\" value=\"True\"/>\n", 
	"                    </attributes>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"expand\">False</property>\n", 
	"                    <property name=\"padding\">2</property>\n", 
	"                    <property name=\"position\">2</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkTreeView\" id=\"treeDone\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"can_focus\">True</property>\n", 
	"                    <property name=\"reorderable\">True</property>\n", 
	"                    <property name=\"fixed_height_mode\">True</property>\n", 
	"                    <property name=\"rubber_banding\">True</property>\n", 
	"                    <property name=\"enable_grid_lines\">horizontal</property>\n", 
	"                    <signal name=\"row_activated\" handler=\"on_treeDoneTransfers_row_activated\"/>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"padding\">3</property>\n", 
	"                    <property name=\"position\">3</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkAlignment\" id=\"alignClearTransfers\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"xalign\">1</property>\n", 
	"                    <property name=\"left_padding\">183</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkButton\" id=\"btnClearTransfers\">\n", 
	"                        <property name=\"label\" translatable=\"yes\">Clear</property>\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"can_focus\">True</property>\n", 
	"                        <property name=\"receives_default\">True</property>\n", 
	"                        <property name=\"border_width\">3</property>\n", 
	"                        <signal name=\"clicked\" handler=\"btnClearTransfers_clicked\"/>\n", 
	"                      </object>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                  <packing>\n", 
	"                    <property name=\"expand\">False</property>\n", 
	"                    <property name=\"position\">4</property>\n", 
	"                  </packing>\n", 
	"                </child>\n", 
	"              </object>\n", 
	"            </child>\n", 
	"            <child type=\"label\">\n", 
	"              <object class=\"GtkLabel\" id=\"frmConnectLbl\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"label\" translatable=\"yes\">Connectage</property>\n", 
	"              </object>\n", 
	"            </child>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"padding\">2</property>\n", 
	"            <property name=\"position\">0</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"        <child>\n", 
	"          <object class=\"GtkVBox\" id=\"vboxRight\">\n", 
	"            <property name=\"visible\">True</property>\n", 
	"            <property name=\"orientation\">vertical</property>\n", 
	"            <child>\n", 
	"              <object class=\"GtkFrame\" id=\"frmFolder\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"label_xalign\">0</property>\n", 
	"                <property name=\"shadow_type\">out</property>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkVBox\" id=\"vboxSaveDir\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"orientation\">vertical</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkHBox\" id=\"hboxDir\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkLabel\" id=\"lblDir\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"label\" translatable=\"yes\">Directory:</property>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"expand\">False</property>\n", 
	"                            <property name=\"fill\">False</property>\n", 
	"                            <property name=\"padding\">4</property>\n", 
	"                            <property name=\"position\">0</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkFileChooserButton\" id=\"btnDirChoice\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"action\">select-folder</property>\n", 
	"                            <property name=\"preview_widget_active\">False</property>\n", 
	"                            <property name=\"title\" translatable=\"yes\">Select A Directory</property>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"position\">1</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"fill\">False</property>\n", 
	"                        <property name=\"position\">0</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkAlignment\" id=\"alignOpenFolder\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"left_padding\">115</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkButton\" id=\"btnOpenFolder\">\n", 
	"                            <property name=\"label\" translatable=\"yes\">Open Folder</property>\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"receives_default\">True</property>\n", 
	"                            <property name=\"border_width\">3</property>\n", 
	"                            <signal name=\"clicked\" handler=\"on_btnOpenFolder_clicked\"/>\n", 
	"                          </object>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"fill\">False</property>\n", 
	"                        <property name=\"position\">1</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                </child>\n", 
	"                <child type=\"label\">\n", 
	"                  <object class=\"GtkLabel\" id=\"frmFolderLbl\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"label\" translatable=\"yes\">Save Folder</property>\n", 
	"                    <property name=\"use_markup\">True</property>\n", 
	"                  </object>\n", 
	"                </child>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">0</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"            <child>\n", 
	"              <object class=\"GtkFrame\" id=\"frmSend\">\n", 
	"                <property name=\"visible\">True</property>\n", 
	"                <property name=\"label_xalign\">0</property>\n", 
	"                <property name=\"shadow_type\">out</property>\n", 
	"                <child>\n", 
	"                  <object class=\"GtkVBox\" id=\"vboxSend\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"orientation\">vertical</property>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkVBox\" id=\"vboxFile\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"orientation\">vertical</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkHBox\" id=\"hboxFile\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <child>\n", 
	"                              <object class=\"GtkLabel\" id=\"lblFile\">\n", 
	"                                <property name=\"visible\">True</property>\n", 
	"                                <property name=\"label\" translatable=\"yes\">File:</property>\n", 
	"                              </object>\n", 
	"                              <packing>\n", 
	"                                <property name=\"expand\">False</property>\n", 
	"                                <property name=\"padding\">4</property>\n", 
	"                                <property name=\"position\">0</property>\n", 
	"                              </packing>\n", 
	"                            </child>\n", 
	"                            <child>\n", 
	"                              <object class=\"GtkFileChooserButton\" id=\"btnFileChoice\">\n", 
	"                                <property name=\"visible\">True</property>\n", 
	"                                <property name=\"title\" translatable=\"yes\">File to Send</property>\n", 
	"                              </object>\n", 
	"                              <packing>\n", 
	"                                <property name=\"position\">1</property>\n", 
	"                              </packing>\n", 
	"                            </child>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"expand\">False</property>\n", 
	"                            <property name=\"position\">0</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkHBox\" id=\"hboxQueue\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"homogeneous\">True</property>\n", 
	"                            <child>\n", 
	"                              <object class=\"GtkButton\" id=\"btnQueue\">\n", 
	"                                <property name=\"label\" translatable=\"yes\">Queue</property>\n", 
	"                                <property name=\"visible\">True</property>\n", 
	"                                <property name=\"can_focus\">True</property>\n", 
	"                                <property name=\"receives_default\">True</property>\n", 
	"                                <property name=\"border_width\">3</property>\n", 
	"                                <signal name=\"clicked\" handler=\"on_btnQueue_clicked\"/>\n", 
	"                              </object>\n", 
	"                              <packing>\n", 
	"                                <property name=\"position\">0</property>\n", 
	"                              </packing>\n", 
	"                            </child>\n", 
	"                            <child>\n", 
	"                              <object class=\"GtkButton\" id=\"btnDequeue\">\n", 
	"                                <property name=\"label\" translatable=\"yes\">Dequeue</property>\n", 
	"                                <property name=\"visible\">True</property>\n", 
	"                                <property name=\"can_focus\">True</property>\n", 
	"                                <property name=\"receives_default\">True</property>\n", 
	"                                <property name=\"border_width\">3</property>\n", 
	"                                <signal name=\"clicked\" handler=\"on_btnDequeue_clicked\"/>\n", 
	"                              </object>\n", 
	"                              <packing>\n", 
	"                                <property name=\"position\">1</property>\n", 
	"                              </packing>\n", 
	"                            </child>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"expand\">False</property>\n", 
	"                            <property name=\"fill\">False</property>\n", 
	"                            <property name=\"position\">1</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"expand\">False</property>\n", 
	"                        <property name=\"position\">0</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkTreeView\" id=\"treeTransfers\">\n", 
	"                        <property name=\"height_request\">100</property>\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"can_focus\">True</property>\n", 
	"                        <property name=\"headers_visible\">False</property>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"position\">1</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkVBox\" id=\"vboxStatus\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"orientation\">vertical</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkLabel\" id=\"lblStatus\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"label\" translatable=\"yes\">Not much going on...</property>\n", 
	"                            <property name=\"justify\">fill</property>\n", 
	"                            <property name=\"wrap\">True</property>\n", 
	"                            <property name=\"wrap_mode\">word-char</property>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"padding\">2</property>\n", 
	"                            <property name=\"position\">0</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkProgressBar\" id=\"progressft\">\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                          </object>\n", 
	"                          <packing>\n", 
	"                            <property name=\"expand\">False</property>\n", 
	"                            <property name=\"fill\">False</property>\n", 
	"                            <property name=\"position\">1</property>\n", 
	"                          </packing>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"fill\">False</property>\n", 
	"                        <property name=\"position\">2</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                    <child>\n", 
	"                      <object class=\"GtkAlignment\" id=\"alignSend\">\n", 
	"                        <property name=\"visible\">True</property>\n", 
	"                        <property name=\"left_padding\">203</property>\n", 
	"                        <child>\n", 
	"                          <object class=\"GtkButton\" id=\"btnSend\">\n", 
	"                            <property name=\"label\" translatable=\"yes\">Send</property>\n", 
	"                            <property name=\"visible\">True</property>\n", 
	"                            <property name=\"can_focus\">True</property>\n", 
	"                            <property name=\"receives_default\">True</property>\n", 
	"                            <property name=\"border_width\">3</property>\n", 
	"                            <signal name=\"clicked\" handler=\"on_btnSend_clicked\"/>\n", 
	"                          </object>\n", 
	"                        </child>\n", 
	"                      </object>\n", 
	"                      <packing>\n", 
	"                        <property name=\"expand\">False</property>\n", 
	"                        <property name=\"fill\">False</property>\n", 
	"                        <property name=\"position\">3</property>\n", 
	"                      </packing>\n", 
	"                    </child>\n", 
	"                  </object>\n", 
	"                </child>\n", 
	"                <child type=\"label\">\n", 
	"                  <object class=\"GtkLabel\" id=\"frmSendLbl\">\n", 
	"                    <property name=\"visible\">True</property>\n", 
	"                    <property name=\"label\" translatable=\"yes\">Sendage</property>\n", 
	"                    <property name=\"use_markup\">True</property>\n", 
	"                  </object>\n", 
	"                </child>\n", 
	"              </object>\n", 
	"              <packing>\n", 
	"                <property name=\"padding\">2</property>\n", 
	"                <property name=\"position\">1</property>\n", 
	"              </packing>\n", 
	"            </child>\n", 
	"          </object>\n", 
	"          <packing>\n", 
	"            <property name=\"position\">1</property>\n", 
	"          </packing>\n", 
	"        </child>\n", 
	"      </object>\n", 
	"    </child>\n", 
	"  </object>\n", 
	"</interface>\n", 
};
#endif
